import Head from "next/head";
import Image from "next/image";
import { getSession } from "next-auth/react";

export default function Home({ user }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header>
          <figure className="avatar">
            <Image
              src={user.image}
              alt={user.name}
              width={60}
              height={60}
              className="avatar__image"
            />
            <figcaption className="avatar__info">
              <h5 className="avatar__name">{user.name}</h5>
              <p className="avatar__email">{user.email}</p>
            </figcaption>
          </figure>
        </header>
      </main>
    </>
  );
}

export const getServerSideProps = async (context) => {
  // Recuperar información almacenada en la Sessión desde el Backend
  const session = await getSession(context);
  return {
    props: {
      user: session.user,
    },
  };
};
